# Site settings
author: Oscar Ore
title: 
header-img: img/home-bg.png
email: oscar.ore2011@gmail.com
copyright_name: Oscar Ore
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Oscar-Ore007

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
